apiVersion: v1
kind: Service
metadata:
  name: {{ include "after-party.fullname" . }}
  labels:
    {{- include "after-party.labels" . | nindent 4 }}
  {{- if .Values.digitalocean.loadBalancer.enabled }}
  annotations:
    {{- toYaml .Values.digitalocean.loadBalancer.annotations | nindent 4 }}
  {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.digitalocean.loadBalancer.enabled }}
  type: LoadBalancer
  {{- else }}
  type: {{ .Values.service.type }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "after-party.selectorLabels" . | nindent 4 }}

